### ISSUE TITLE
BE: Contest Controllers

### ISSUE THREAD

**Issue by bonnieli** [hatchways/team-hummingbird#12]
- CREATE /contest
-- Given parameters passed in, create a contest. 
- UPDATE /contest/:id 
-- Given an ID and new parameters, update the contest
- GET /contest/:id
-- Given an ID, return contest with that ID
- GET /contests
-- A list of contests that are available for submission
-

**Comment by patelparth1993** [comment]
@bonnieli 
GET /contests-->is contest's' a typo here? All other are /contest
